ShellCheck cleanup

diff --git a/sync-be b/sync-be
--- a/sync-be
+++ b/sync-be
@@ -26,8 +26,8 @@
 # OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 # SUCH DAMAGE.
 
-if [ -z "$1" -o -z "$2" ]; then
-    echo "usage: $(basename $0) <new_bootenv> <bootenv_config>"
+if [ -z "$1" ] || [ -z "$2" ]; then
+    echo "usage: $(basename "$0") <new_bootenv> <bootenv_config>"
     exit 1
 fi
 
@@ -35,7 +35,7 @@ BENAME=$1
 BECONF=$2
 OLDMP=
 NEWMP=
-UDATE=`date -u +%Y%m%d-%H%M`
+UDATE=$(date -u +%Y%m%d-%H%M)
 
 [ "${BECONF#/}" = "${BECONF}" ] && \
     BECONF="$(pwd)/${BECONF}"
@@ -50,28 +50,28 @@ echo "using config file: $BECONF"
 sync() {
     _pwd=$(pwd)
 
-    cd $OLDMP
-    egrep -v '^#' $BECONF | while read glob; do
+    cd $OLDMP || exit 1
+    grep -Ev '^#' "$BECONF" | while read -r glob; do
 
         # force relative paths from config file
         glob=${glob#/}
-        find $glob -quit 2> /dev/null || continue
+        find "$glob" -quit 2> /dev/null || continue
 
         for file in $glob; do
             # overwrite directory in the new boot environment
-            if [ -d "$file" ] && [ -d $NEWMP/$file ]; then
-                if ! rm -rf $NEWMP/$file; then
-                    echo "error: unable to remove $NEWMP/$file, exiting.."
+            if [ -d "$file" ] && [ -d "$NEWMP"/"$file" ]; then
+                if ! rm -rf "${NEWMP:?}"/"$file"; then
+                    echo "error: unable to remove $NEWMP/$file, exiting..."
                     exit 1
                 fi
             elif [ -f "$file" ]; then
                 # make sure directory exists where file is being installed
-                dir=$(dirname $NEWMP/$file)
-                [ ! -d "$dir" ] && mkdir -p $dir
+                dir=$(dirname "$NEWMP"/"$file")
+                [ ! -d "$dir" ] && mkdir -p "$dir"
             fi
 
             echo "copying $file to $NEWMP/$file"
-            if ! cp -vfa $file $NEWMP/$file; then
+            if ! cp -vfa "$file" "$NEWMP"/"$file"; then
                 echo "error: failed to copy, exiting!"
                 exit 1
             fi
@@ -79,16 +79,16 @@ sync() {
 
     done;
 
-    cd ${_pwd}
+    cd "${_pwd}" || exit 1
 }
 
 cleanup() {
-    umount $NEWMP
-    rmdir $NEWMP
+    umount "$NEWMP"
+    rmdir "$NEWMP"
 }
 
 # use the dataset that is being booted from
-ROOTFS=`mount -p | awk '$2 == "/" && $3 == "zfs" { print $1 }'`
+ROOTFS=$(mount -p | awk '$2 == "/" && $3 == "zfs" { print $1 }')
 if [ -z "$ROOTFS" ]; then
     echo "error: zfs is not on root"
     exit 1
@@ -96,27 +96,26 @@ fi
 
 # sanity check between booted root fs and bootfs
 zpool="${ROOTFS%%/*}"
-BOOTFS=`zpool get -H -o value bootfs ${zpool}| awk '$0 != "-" { print $0 }'`
+BOOTFS=$(zpool get -H -o value bootfs "${zpool}" | awk '$0 != "-" { print $0 }')
 if [ "$ROOTFS" != "$BOOTFS" ]; then
-    echo "WARNING:  ZFS on rootfs doesn't match bootfs, continuing.."
-    echo "          bootfs=$BOOTFS, rootfs=$ROOTFS"
+    echo "WARNING: ZFS on rootfs doesn't match bootfs, continuing..."
+    echo "         bootfs=$BOOTFS, rootfs=$ROOTFS"
 fi
 
 
-BEPATH="$(dirname $ROOTFS)/$BENAME"
-if ! zfs recv -Fuv $BEPATH; then
+BEPATH=$(dirname "$ROOTFS")/$BENAME
+if ! zfs recv -Fuv "$BEPATH"; then
     echo "error: zfs receive failed, exiting!"
     exit 1
 fi
 
 OLDMP="/"
-NEWMP=`mktemp -d -t klara`
-if [ $? -ne 0 ]; then
+if ! NEWMP=$(mktemp -d -tsync); then
     echo "error: failed to create temporary mountpoint"
     exit 1
 fi
 
-if ! mount -t zfs $BEPATH $NEWMP; then
+if ! mount -t zfs "$BEPATH" "$NEWMP"; then
     echo "error: failed to mount $BEPATH at $NEWMP"
     exit 1
 fi
@@ -125,12 +124,12 @@ if ! sync; then
     cleanup
 fi
 
-if ! zfs snapshot $BOOTFS@syncbe:$UDATE; then
+if ! zfs snapshot "$BOOTFS"@syncbe:"$UDATE"; then
     echo "error: failed to create $BOOTFS@syncbe:$UDATE snapshot"
     exit 1
 fi
 
-if ! zfs snapshot $BEPATH@syncbe:$UDATE; then
+if ! zfs snapshot "$BEPATH"@syncbe:"$UDATE"; then
     echo "error: failed to create $BEPATH@syncbe:$UDATE snapshot"
     exit 1
 fi
